### ISSUE TITLE
Version 7.0.0 is not created

### ISSUE THREAD

**Issue by aninde** [handsontable/examples#3]
#### Description
Version 7.0.0 is not created.

After loading as a handsontable 7.0.0 dependency, codesandbox asks you to load core-js.
![Screenshot 2020-02-17 at 16 05 06](https://user-images.githubusercontent.com/30186818/74665263-a3530b80-519f-11ea-82d4-edf869c6d992.png)

After pressing the button the module is not searched anyway.
![Screenshot 2020-02-17 at 16 05 22](https://user-images.githubusercontent.com/30186818/74665267-a51ccf00-519f-11ea-81e8-02e2a5bac470.png)

**Comment by wojciechczerniak** [comment]
Fixed in a later version of Handsontable

https://github.com/handsontable/handsontable/issues/5888
